-- 자료실 DATA_ROOM / DATA_ROOM_FILE
-- 실행 DB: [돌봄시설DB]
-- 게시글(DATA_ROOM) 1건에 첨부파일(DATA_ROOM_FILE) 최대 10개

IF OBJECT_ID(N'[돌봄시설DB].[dbo].[DATA_ROOM]', N'U') IS NULL
BEGIN
  CREATE TABLE [돌봄시설DB].[dbo].[DATA_ROOM] (
    [DR_SEQ]         INT IDENTITY(1,1) NOT NULL,
    [ANCD]           INT NOT NULL,
    [CATEGORY]       NVARCHAR(20) NOT NULL,
    [TITLE]          NVARCHAR(200) NOT NULL,
    [DESCRIPTION]    NVARCHAR(2000) NULL,
    [FILE_NAME]      NVARCHAR(260) NULL,
    [BLOB_NAME]      NVARCHAR(500) NULL,
    [CONTENT_TYPE]   NVARCHAR(120) NULL,
    [FILE_SIZE]      BIGINT NULL,
    [DOWNLOAD_CNT]   INT NOT NULL CONSTRAINT [DF_DATA_ROOM_DOWNLOAD_CNT] DEFAULT (0),
    [REG_EMPNO]      NVARCHAR(20) NULL,
    [REG_EMPNM]      NVARCHAR(100) NULL,
    [REG_DATE]       DATETIME NULL,
    [MOD_EMPNO]      NVARCHAR(20) NULL,
    [MOD_DATE]       DATETIME NULL,
    CONSTRAINT [PK_DATA_ROOM] PRIMARY KEY CLUSTERED ([DR_SEQ])
  );
END
GO

IF OBJECT_ID(N'[돌봄시설DB].[dbo].[DATA_ROOM_FILE]', N'U') IS NULL
BEGIN
  CREATE TABLE [돌봄시설DB].[dbo].[DATA_ROOM_FILE] (
    [DRF_SEQ]        INT IDENTITY(1,1) NOT NULL,
    [DR_SEQ]         INT NOT NULL,
    [ANCD]           INT NOT NULL,
    [FILE_NAME]      NVARCHAR(260) NOT NULL,
    [BLOB_NAME]      NVARCHAR(500) NOT NULL,
    [CONTENT_TYPE]   NVARCHAR(120) NULL,
    [FILE_SIZE]      BIGINT NOT NULL CONSTRAINT [DF_DATA_ROOM_FILE_SIZE2] DEFAULT (0),
    [DOWNLOAD_CNT]   INT NOT NULL CONSTRAINT [DF_DATA_ROOM_FILE_DL] DEFAULT (0),
    [SORT_ORD]       INT NOT NULL CONSTRAINT [DF_DATA_ROOM_FILE_ORD] DEFAULT (0),
    [REG_DATE]       DATETIME NULL,
    CONSTRAINT [PK_DATA_ROOM_FILE] PRIMARY KEY CLUSTERED ([DRF_SEQ])
  );
  CREATE NONCLUSTERED INDEX [IX_DATA_ROOM_FILE_DR_SEQ]
    ON [돌봄시설DB].[dbo].[DATA_ROOM_FILE] ([DR_SEQ], [SORT_ORD], [DRF_SEQ]);
END
GO
