# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - health-care-program

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: npm install
        run: npm ci --only=production

      - name: npm run build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Verify .next folder exists
        run: |
          if [ ! -d ".next" ]; then
            echo "ERROR: .next folder was not created during build"
            ls -la
            exit 1
          fi
          echo ".next folder created successfully"
          ls -la .next/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .
            !node_modules
            !.git
            !.github
            !*.log

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A58952C5E0294554BC598632201E412B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2E5861F0922D40CDA20204A3ED82265A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F5973AFBAA454C47A894C22BA8791F8A }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'health-care-program'
          slot-name: 'Production'
          package: .
